version: '2.4'

services:

  db:
    image: postgres:10.6
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres:/var/lib/postgresql/data/pgdata

  odoo:
    image: ghcr.io/moka-mourisme/docker-moka:14.0
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_USER: bot-moka
        GITHUB_TOKEN: _REPLACE_WITH_GITHUB_X_ACCESS_TOKEN_
    environment:
      TZ: Europe/Paris
      LOG_LEVEL: info
      ADMIN_PASSWORD: admin
      WORKERS: 2
      LIMIT_TIME_CPU: 240
      LIMIT_TIME_REAL: 360
      LIMIT_MEMORY_SOFT: 5368709120
      LIMIT_MEMORY_HARD: 10737418240
      # Postgres
      PGHOST: db
      PGUSER: odoo
      PGPASSWORD: odoo
    init: true
    tty: true
    stdin_open: true
    depends_on:
      - db
    ports:
      - 8069:8069
    volumes:
      - filestore:/home/odoo/data
      # These modules are loaded with higher priority than the ones in the image
      # If a module has the same name, this one will be used.
      - ./custom_code:/home/odoo/custom/repositories:rw,z

volumes:
  postgres:
  filestore:
