name: ci

on:
  pull_request:
    branches:
      - "15.0"
  push:
    branches:
      - "15.0"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPO: moka-tourisme/docker-moka
      DOCKER_TAG: "15.0"
    steps:
      # Prepare
      - name: Checkout
        uses: actions/checkout@v2
      # Setup Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        # Login ghcr.io
      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # Build image
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          build-args: |
            GIT_SHA1=${{ github.sha }}
            GITHUB_USER="bot-moka"
            GITHUB_TOKEN=${{ secrets.MOKA_BOT_GITHUB_TOKEN }}
          tags: ${{env.DOCKER_REPO}}:${{env.DOCKER_TAG}}
          labels: org.opencontainers.image.source=${{ github.event.repository.html_url }}
          cache-from: type=registry,ref=ghcr.io/${{env.DOCKER_REPO}}:${{env.DOCKER_TAG}}
          cache-to: type=local,dest=/tmp/.buildx-cache
          load: true
          pull: true
      # Push
      - name: Push
        if: ${{ github.event_name == 'push' }}
        run: |
          docker tag ${{env.DOCKER_REPO}}:${{env.DOCKER_TAG}} ghcr.io/${{env.DOCKER_REPO}}:${{env.DOCKER_TAG}}
          docker push ghcr.io/${{env.DOCKER_REPO}}:${{env.DOCKER_TAG}}
